[package]
name = "browser"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_egui = "0.34.1"
tokio = { version = "1", features = ["full"] }
futures-lite = "1.13"
reqwest = { version = "0.12", features = ["json", "blocking"], default-features = false }
